### ISSUE TITLE
visulisation error

### ISSUE THREAD

**Issue by policycompassccc** [policycompass/featureboard#50]
Error when trying to cancel the visualisation at policy compass 4th session. 
[issue_visulisation.docx](https://github.com/policycompass/featureboard/files/182531/issue_visulisation.docx)

**Comment by cbotsikas** [comment]
@policycompassccc Thank you for reporting this bug. Resolution progress can be seen at https://github.com/policycompass/policycompass/issues/508.

By the way, you can report bugs directly on our issue tracker at https://github.com/policycompass/policycompass/issues instead of this board which is intended for platform feature requests.
